name: hello-world
on: push
jobs:
  hello-world-job:
    runs-on:  ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3  

      - run: echo "$(cat hello_world.txt)"

      - name: Send Email Notification
        uses: dawidd6/action-send-mail@v3.12.0
        with:
          server_address: "{{localhost}}"
          subject: git-mail-testtt
          # Recipients mail addresses (separated with comma)
          to: sriranjan.m@intel.com
          # Full name of mail sender (might be with an email address specified in <>)
          from: git_test@gitaction.com
          # Body of mail message (might be a filename prefixed with file:// to read from)
          body: git-mail-testtt
          # HTML body of mail message (might be a filename prefixed with file:// to read from)
          
          
            
