name: hello-world
on: push
jobs:
  hello-world-job:
    runs-on:  ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3  

      - run: echo "$(cat hello_world.txt)"

      - name: Send Email Notification
        env:
          TO_EMAIL: sriranjan.m@intel.com  # Adjust recipient email address
          FROM_EMAIL: git@example.com  # Adjust sender email address
          SUBJECT: "Notification: Changes pushed to ${{ github.repository }}"  # Adjust email subject
        run: |
          echo "Changes have been pushed to ${{ github.repository }}. Check the repository for details." | mail -s "$SUBJECT" -r "$FROM_EMAIL" "$TO_EMAIL"
            
